apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-in-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-in-k8s
  template:
    metadata:
      labels:
        app: cluster-in-k8s
    spec:
      containers:
      - image: okteto.dev/cluster-in-k8s
        name: cluster-in-k8s